#include "ex.h"

static struct {
	const char *sname;
	const char *lname;
	void (*fn)();
} ex_commands[] = {
	{ "ab",		"abbreviate",	ex_abbreviate },
	{ "a",		"append",	ex_append },
	{ "ar",		"args",		ex_args },
	{ "c",		"change",	ex_change },
	{ "chd",	"chdir",	ex_chdir },
	{ "co",		"copy",		ex_copy },
	{ "t",		"t",		ex_copy },
	{ "d",		"delete",	ex_delete },
	{ "e",		"edit",		ex_edit },
	{ "f",		"file",		ex_file },
	{ "g",		"global",	ex_global },
	{ "v",		"v",		ex_global },
	{ "i",		"insert",	ex_insert },
	{ "j",		"join",		ex_join },
	{ "l",		"list",		ex_list },
	{ "map",	"map",		ex_map },
	{ "ma",		"mark",		ex_mark },
	{ "k",		"k",		ex_mark },
	{ "m",		"move",		ex_move },
	{ "n",		"next",		ex_next },
	{ "nu",		"number",	ex_number },
	{ "#",		"#",		ex_number },
	{ "o",		"open",		ex_open },
	{ "pre",	"preserve",	ex_preserve },
	{ "p",		"print",	ex_print },
	{ "pu",		"put",		ex_put },
	{ "q",		"quit",		ex_quit },
	{ "r",		"read",		ex_read },
	{ "rec",	"recover",	ex_recover },
	{ "rew",	"rewind",	ex_rewind },
	{ "se",		"set",		ex_set },
	{ "sh",		"shell",	ex_shell },
	{ "so",		"source",	ex_source },
	{ "s",		"substitute",	ex_substitute },
	{ "&",		"&",		ex_ampersand },
	{ "~",		"~",		ex_tilde },
	{ "su",		"suspend",	ex_suspend },
	{ "ta",		"tag",		ex_tag },
	{ "una",	"unabbrev",	ex_unabbrev },
	{ "u",		"undo",		ex_undo },
	{ "unm",	"unmap",	ex_unmap },
	{ "ve",		"version",	ex_version },
	{ "vi",		"visual",	ex_visual },
	{ "w",		"write",	ex_write },
	{ "wq",		"wq",		ex_wq },
	{ "x",		"xit",		ex_xit },
};
